# dbt_project.yml

name: dbtdemo
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
seed-paths: ["data"]
snapshot-paths: ["snapshots"]

models:
  dbtdemo:
    +materialized: view  # Set the default materialization to view
    final_transaction_details:
      +materialized: table  # Override for the final model to be a table